package com.company.www.constant.no_use;


import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Authority {
    ADMINISTRATOR("ADMINISTRATOR"),
    GENERAL_MANAGER("GENERAL_MANAGER"),
    SALES_DIRECTOR("SALES_DIRECTOR"),
    ACCOUNT_DIRECTOR("ACCOUNT_DIRECTOR"),
    FINANCE_DIRECTOR("FINANCE_DIRECTOR"),
    HUMAN_RESOURCE_DIRECTOR("HUMAN_RESOURCE_DIRECTOR"),
    DESIGN_DIRECTOR("DESIGN_DIRECTOR"),
    INFORMATION_DIRECTOR("INFORMATION_DIRECTOR"),
    SALES_MANAGER("SALES_MANAGER"),
    ACCOUNT_MANAGER("ACCOUNT_MANAGER"),
    FINANCE_MANAGER("FINANCE_MANAGER"),
    HUMAN_RESOURCE_MANAGER("HUMAN_RESOURCE_MANAGER"),
    DESIGN_MANAGER("DESIGN_MANAGER"),
    INFORMATION_MANAGER("INFORMATION_MANAGER"),
    SALES_STAFF("SALES_STAFF"),
    ACCOUNT_STAFF("ACCOUNT_STAFF"),
    FINANCE_STAFF("FINANCE_STAFF"),
    HUMAN_RESOURCE_STAFF("HUMAN_RESOURCE_STAFF"),
    DESIGN_STAFF("DESIGN_STAFF"),
    INFORMATION_STAFF("INFORMATION_STAFF"),
    STAFF("STAFF");

    private final String code;
}